language: node_js
node_js:
- 12
script:
- npm run build-ci
before_deploy:
- cd dist/angular-icalendar
deploy:
  provider: npm
  email: theo.godard@gmail.com
  skip_cleanup: true
  api_key:
    secure: Y5Z4AaD/lqIYK5uZCFNuRLWxYxft4i0htZt9BAzez/E4YmmQ3yc0mHjsLHkfqA13fN6idj/Fbb9h6tQMCYh/+d4IMqR5T6Z/L947BVXDxA8k3+2b6Q0knl/HlvptLzvm9i1MC6NYthVI9SO7xZevXJtdh1FR1xP4MIEAVDbEV9qTec4wVwLz2UkJTN/Qg6xAiyde3VRuwVvMehk0PWgI8w5IXGbhIYS/KxxFp3/zmBimWXjpioP/6ri7GqukYJI+K76ZhT3kXcq3M1w2BEofqOmDhLswCALhA6KRrLhWYE3FkxHmFKvRnrshmtjFNWDy0UHzjfmtF/iQZ+iyscQhzSSM6m4yOXW3hqi7fbkFxv/HVmY0kzW+c6LeSKaAsQo5dwLDjSwd3qc8qu5rG62H9EJ5giI1mQNIDqsc+4lB+Q19epQNQ69LS+ns7cORJo3dVkT32cyMilZ6Yb2ne92lhAF+k2aw4g+e62zVmbOCVY3FvNA5sZcq/yZ3YWeqlV3mhqpmwTFY0eSmZ84dvx671WsvSJqcmIdjKWbeflmOnNb0sKd2ALb73Xsh1nYrHqtFVxsWaiw8NHnithitI6wdUfGUNEu8jaw2MLMTkwI/jl9/yVhjtxuXcR5yIUmz1XktxbYamqtf0rdcdV+itYzWiL8PBVchMaUwcpoKbyfpGeU=
  on:
    repo: godardth/angular-icalendar
